### ISSUE TITLE
Aborted while executing tokens.js!

### ISSUE THREAD

**Issue by LiWeny16** [amper5and/voice.js#25]

**Comment by LiWeny16** [comment]
## Details for the errors:
``` js
node .\tokens.js
.rnr error:  Error
    at new module.exports (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\lib\voicejs.errors.js:7:16)
    at C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:92:10
    at GoogleClientLogin.fullCallback (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:12:3)
    at Object.onceWrapper (node:events:646:26)
    at GoogleClientLogin.emit (node:events:526:28)
    at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:149:12)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 1,
  message: 'LOGIN_ERROR',
  details: Error: Login failed
      at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:146:15)
      at IncomingMessage.emit (node:events:538:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
    response: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: null,
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
.gvx error:  Error
    at new module.exports (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\lib\voicejs.errors.js:7:16)
    at C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:92:10
    at GoogleClientLogin.fullCallback (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:12:3)
    at Object.onceWrapper (node:events:646:26)
    at GoogleClientLogin.emit (node:events:526:28)
    at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:149:12)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 1,
  message: 'LOGIN_ERROR',
  details: Error: Login failed
      at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:146:15)
      at IncomingMessage.emit (node:events:538:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
    response: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: null,
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
.auth error:  Error
    at new module.exports (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\lib\voicejs.errors.js:7:16)
    at C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:92:10
    at GoogleClientLogin.fullCallback (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\voice.js:12:3)
    at Object.onceWrapper (node:events:646:26)
    at GoogleClientLogin.emit (node:events:526:28)
    at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:149:12)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 1,
  message: 'LOGIN_ERROR',
  details: Error: Login failed
      at GoogleClientLogin.<anonymous> (C:\Learning\sample\node.js-Php\Bigproject\GoogleVoice\voice.js-master\node_modules\googleclientlogin\index.js:146:15)
      at IncomingMessage.emit (node:events:538:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    data: 'https://developers.google.com/accounts/docs/AuthForInstalledApps\n',
    response: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: null,
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
```


## Can anyone help me figure out this problem?
